const nigeriaLocations = {
  "Abia": ["Umuahia", "Aba", "Ohafia"],
  "Adamawa": ["Yola", "Mubi", "Numan"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene"],
  "Anambra": ["Awka", "Onitsha", "Nnewi"],
  "Bauchi": ["Bauchi", "Azare", "Misau"],
  "Bayelsa": ["Yenagoa", "Brass", "Ogbia"],
  "Benue": ["Makurdi", "Gboko", "Otukpo"],
  "Borno": ["Maiduguri", "Biu", "Dikwa"],
  "Cross River": ["Calabar", "Ikom", "Ogoja"],
  "Delta": ["Asaba", "Warri", "Sapele", "Agbor"],
  "Ebonyi": ["Abakaliki", "Afikpo"],
  "Edo": ["Benin City", "Auchi", "Ekpoma"],
  "Ekiti": ["Ado Ekiti", "Ikere", "Iyin Ekiti"],
  "Enugu": ["Enugu", "Nsukka", "Awgu"],
  "Gombe": ["Gombe", "Kaltungo"],
  "Imo": ["Owerri", "Orlu", "Okigwe"],
  "Jigawa": ["Dutse", "Hadejia", "Kazaure"],
  "Kaduna": ["Kaduna", "Zaria", "Kafanchan"],
  "Kano": ["Kano", "Wudil", "Gwarzo"],
  "Katsina": ["Katsina", "Daura", "Funtua"],
  "Kebbi": ["Birnin Kebbi", "Argungu", "Yauri"],
  "Kogi": ["Lokoja", "Okene", "Idah"],
  "Kwara": ["Ilorin", "Offa", "Lafiagi"],
  "Lagos": ["Ikeja", "Ikorodu", "Epe", "Badagry"],
  "Nasarawa": ["Lafia", "Keffi", "Akwanga"],
  "Niger": ["Minna", "Bida", "Kontagora"],
  "Ogun": ["Abeokuta", "Ijebu Ode", "Sagamu"],
  "Ondo": ["Akure", "Ondo Town", "Owo"],
  "Osun": ["Oshogbo", "Ilesa", "Iwo"],
  "Oyo": ["Ibadan", "Ogbomoso", "Oyo"],
  "Plateau": ["Jos", "Pankshin", "Shendam"],
  "Rivers": ["Port Harcourt", "Bonny", "Omoku"],
  "Sokoto": ["Sokoto", "Tambuwal"],
  "Taraba": ["Jalingo", "Wukari", "Bali"],
  "Yobe": ["Damaturu", "Potiskum", "Gashua"],
  "Zamfara": ["Gusau", "Kaura Namoda", "Anka"],
  "FCT": ["Abuja"]
};
